version: '4.3'
services:
  DBMS1:
    image: mongo:latest
    container_name: DBMS1
    ports:
      - "27017:27017"
    volumes:
      - ./init-scripts/mongo-init1.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - mongo-net

  DBMS2:
    image: mongo:latest
    container_name: DBMS2
    ports:
      - "27018:27017"
    volumes:
      - ./init-scripts/mongo-init2.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - mongo-net

  GFS:
    image: mongo:latest
    container_name: GFS
    ports:
      - "27041:27017"
    volumes:
      - ./init-scripts/mongo-init2.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - mongo-net

networks:
  mongo-net:
